# -*- coding: utf-8 -*-
"""patent-phrase-similarity-transformer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pTnzJCgIuWFKjP6xSbbI8osET8-AqMDv
"""

!pip install -q datasets transformers evaluate accelerate

from datasets import load_dataset

ds = load_dataset("tasksource/patent-phrase-similarity")
ds

import pandas as pd

df=ds["train"].to_pandas()
df.head()

df.columns

print("Shape:", df.shape)

print("\nColumns:")
print(df.columns)

print("\nFirst rows:")
display(df.head())

print("\nInfo:")
df.info()

print("\nMissing values:")
print(df.isna().sum())

print("\nScore distribution:")
print(df["score"].value_counts().sort_index())

print("\nUnique values:")
print("Unique anchors:", df["anchor"].nunique())
print("Unique targets:", df["target"].nunique())
print("Unique contexts:", df["context"].nunique())

print("\nTop contexts:")
print(df["context"].value_counts().head(10))

df["input"] = (
    "Anchor: " + df["anchor"] +
    " Target: " + df["target"] +
    " Context: " + df["context"]
)

df[["input", "score"]].head()

!pip install -q transformers

from transformers import AutoTokenizer

model_nm = "microsoft/deberta-v3-small"
tokz = AutoTokenizer.from_pretrained(model_nm)

from sklearn.model_selection import train_test_split

train_df, valid_df = train_test_split(
    df,
    test_size=0.2,
    random_state=42,
    stratify=df["score"]
)

train_df.shape, valid_df.shape

from datasets import Dataset, DatasetDict

train_ds = Dataset.from_pandas(train_df.reset_index(drop=True))
valid_ds = Dataset.from_pandas(valid_df.reset_index(drop=True))

ds = DatasetDict({
    "train": train_ds,
    "valid": valid_ds
})

ds

def tok_func(batch):
    return tokz(
        batch["input"],
        truncation=True,
        max_length=128)

tok_ds = ds.map(tok_func, batched=True)

tok_ds

tok_ds = tok_ds.rename_column("score", "labels")

remove_cols = [
    "anchor", "target", "rating", "context", "label", "input"
]

tok_ds = tok_ds.remove_columns(remove_cols)

tok_ds["train"].column_names

import numpy as np
import torch
from transformers import (
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer,
    DataCollatorWithPadding
)

# مطمئن شو label ها float هستند
def make_labels_float(example):
    example["labels"] = float(example["labels"])
    return example

tok_ds = tok_ds.map(make_labels_float)

# مدل را از صفر دوباره بساز
model = AutoModelForSequenceClassification.from_pretrained(
    model_nm,
    num_labels=1,
    problem_type="regression"
)

# مهم: مدل را صریحاً float32 کن
model = model.float()

# metric امن
def corr(eval_pred):
    preds, labels = eval_pred
    preds = preds.squeeze()

    if np.isnan(preds).any():
        return {"pearson": 0.0}

    if np.std(preds) == 0 or np.std(labels) == 0:
        return {"pearson": 0.0}

    return {"pearson": np.corrcoef(preds, labels)[0][1]}

data_collator = DataCollatorWithPadding(tokenizer=tokz)

args = TrainingArguments(
    output_dir="patent_similarity_model_v3",
    learning_rate=1e-5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=3,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    logging_strategy="epoch",
    report_to="none",

    # مهم‌ترین قسمت برای حل خطا
    fp16=False,
    bf16=False
)

trainer = Trainer(
    model=model,
    args=args,
    train_dataset=tok_ds["train"],
    eval_dataset=tok_ds["valid"],
    processing_class=tokz,
    data_collator=data_collator,
    compute_metrics=corr
)

trainer.train()

eval_result = trainer.evaluate()
eval_result

eval_result = trainer.evaluate()
eval_result

pred_output = trainer.predict(tok_ds["valid"])
pred_output

import numpy as np

preds = pred_output.predictions.squeeze()
labels = pred_output.label_ids

preds[:10], labels[:10]

preds_clipped = np.clip(preds, 0, 1)

from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

pearson = np.corrcoef(preds_clipped, labels)[0][1]
mae = mean_absolute_error(labels, preds_clipped)
rmse = mean_squared_error(labels, preds_clipped) ** 0.5

print("Pearson:", pearson)
print("MAE:", mae)
print("RMSE:", rmse)

valid_results = valid_df.reset_index(drop=True).copy()

valid_results["pred"] = preds_clipped
valid_results["error"] = abs(valid_results["score"] - valid_results["pred"])

valid_results[["anchor", "target", "context", "score", "pred", "error"]].head(10)

valid_results.sort_values("error").head(10)[
    ["anchor", "target", "context", "score", "pred", "error"]
]

def predict_similarity(anchor, target, context):
    text = f"Anchor: {anchor} [SEP] Target: {target} [SEP] Context: {context}"

    inputs = tokz(
        text,
        return_tensors="pt",
        truncation=True,
        max_length=128
    )

    inputs = {k: v.to(model.device) for k, v in inputs.items()}

    output = model(**inputs)
    pred = output.logits.item()
    pred = max(0, min(1, pred))

    return pred

predict_similarity("car engine", "vehicle motor", "B60")

predict_similarity("car engine", "banana peel", "B60")